name:                hwordle
version:             0.1.0.0
github:              "zhaose233/hwordle"
license:             GPL-3.0
author:              "Zhaose"
maintainer:          "zhaose233@outlook.com"
copyright:           "2025 Zhaose"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/zhaose233/hwordle#readme>

dependencies:
- base >= 4.7 && < 5
- random
- rainbow
- text

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -XOverloadedStrings

library:
  source-dirs: src

executables:
  hwordle-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hwordle

tests:
  hwordle-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hwordle
